#!/usr/bin/env ruby
# Id$ nonnax 2022-04-04 21:44:47 +0800
require_relative 'lib/flixml'

#
# run templater
#
active = ARGV.pop  # ARGV sets active page for navlink

s=tagu(true) do
    ARGF.each_line(chomp: true) do |l|
      unless l.match?(/\t/)
        # File.write('active.txt', l)
        next
      end
      div!(class: 'item') do
        l.split(/\t/) => [img, title, href]
        a!( href: , target: '_blank'){img! src: img, title: }
        br!
        a!( href: , target: '_blank'){title}
      end
    end
  end

doc=layout(active:) do
  s.to_s
end

puts doc
