#!/usr/bin/env ruby
# Id$ nonnax 2022-02-26 17:07:45 +0800
path='./site/public/views'

cmds=
[
  "./flixer mov 1  | ./flixml.rb mov > #{path}/movie.erb",
  "./flixer tv 1    | ./flixml.rb tv > #{path}/tv.erb",
  "./make_index.rb  | ./flixml.rb index > #{path}/index.erb",
]

cmds.each do |cmd|
  IO.popen(cmd, &:read)
end

